config/routes.rb
Rails.application.routes.draw do
  #post 'users/create'
  #post 'users/login'
  resources :users
  resources :articles do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  validates_presence_of :title
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  has_rich_text :content
  validates_presence_of :content
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_secure_password :recovery_password, validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  
  
  # GET /articles or /articles.json
  def index
    @articles = Article.all
    @user = User.last
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  
  
  
  def create 
    @article.comments.create! params.required(:comment).permit(:content)
    redirect_to @article 
  end
  
  private
  def set_article
    @article = Article.find params[:article_id]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # GET /users/new
  def new
    @user = User.new
  end
  # POST /users/new
  def create
    @user = User.new
    @user.name = params[:user][:name]  
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    puts "user name: #{@user.name}, user password: #{@user.password}" 
    redirect_to articles_path if @user.save
  end
  
  # GET /users/login
  def login
  end
  
  # POST /users/login
  def log_in
    @user = User.find params[:user][:name] 
    if @user.password == params[:user][:password]
      give_token
    else
      redirect_to articles_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="container-fluid" id="<%= dom_id article %>" >
  <p>
    <h3><%= article.title %><h6><span class="badge rounded-pill bg-primary">Created <%= time_tag article.created_at, "data_local": "time-ago" %></span></h6></h3>
  </p>
	

	<div class="card">
		<div class="card-body">
    	<%= article.content %>
		</div>
	</div>

</div>

app/views/articles/_comment.html.erb
<h5><span class="badge rounded-pill bg-primary"> <%= pluralize article.comments.count, "Comments" %></span></h5>

<div id="comments">
	<% article.comments.each do |comment| %>
		<div class="card" style="border-width: 1px; background-color: #f6f3f3; width: 25rem">
	  	<div class="card-body">
				<%= render comment %>
			</div>
		</div>
		<br>
	<% end %>
</div>


<%= render "comments/new", article: article %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container-fluid">
<h3>Editing article</h3>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid"><h1>Cardinal Gem</h1>
<div id="users">
	<% if @user and @user.save %>
		<p align="right">User: <%= @user.name  %></p>
		<% else %>
		<div align="right"><%= link_to "Create user", new_user_path %></div>
	<% end %>
</div>
</div>

<div id="articles" class="container-fluid">
  <% @articles.each do |article| %>
		<div class="card border-danger" style="border-width: 3px; background-color: #f6f3f3">
	  	<div class="card-body">
    		<%= render article %>
			</div>
			<span class="align-middle"><%= link_to "Show this article", article %></span>
		</div>
		<br>
  <% end %>
	<span class="align-middle"><%= link_to "New article", new_article_path %></span>
</div>
<br>

app/views/articles/new.html.erb
<div class="container-fluid">
<h3>New article</h3>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container-fluid">
	<%= render @article %>
</div>
<br>
<div class="container-fluid">
	<%= render "articles/comment", article: @article %>
</div>
<br>

<div class="container-fluid">
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>
  <br>
  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
	<%= comment.content %>
	-<%= time_tag comment.created_at, "data-local": "time-ago" %>
</div>

app/views/comments/_new.html.erb
<h5>Create comment</h5>
<%= form_with model: [ article, Comment.new ] do |form| %>
	<%= form.rich_text_area :content %>
	<%= form.submit %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardinalGem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/new.html.erb
<div class="container-fluid">
<h3>Create user</h3>
<%= form_with model: @user do |form| %>
	<div>
   	<%= form.label :name, style: "display: block" %>
   	<%= form.text_field :name %>
	</div>
	<div>
   	<%= form.label :password, style: "display: block" %>
   	<%= form.text_field :password %>
	</div>
	<div>
   	<%= form.label :password_confirmation, style: "display: block" %>
   	<%= form.text_field :password_confirmation %>
	</div>
	<div>
	 <%= form.submit %>
	</div>
<% end %>
</div>